import { useState } from 'react';
import FindingCard from './FindingCard';

const STATUS_EMOJI = { high: '🔴', low: '🔴', slightly_high: '🟡', slightly_low: '🟡', normal: '🟢' };

function buildWhatsAppMessage(data) {
  const findings   = data.findings || [];
  const abnormal   = findings.filter(f => f.status !== 'normal');

  let msg = `🏥 *ReportSamjho — Meri Medical Report*\n\n`;

  if (data.overall_summary) {
    msg += `📋 *Report Summary*\n${data.overall_summary}\n\n`;
  }

  if (abnormal.length > 0) {
    msg += `⚠️ *Dhyan dene wali values (${abnormal.length})*\n`;
    msg += `${'─'.repeat(30)}\n`;
    abnormal.forEach((f) => {
      const emoji = STATUS_EMOJI[f.status] || '⚪';
      msg += `\n${emoji} *${f.parameter_name_en}`;
      if (f.parameter_name_local && f.parameter_name_local !== f.parameter_name_en) {
        msg += ` / ${f.parameter_name_local}`;
      }
      msg += `*\n`;
      msg += `📊 Value: *${f.value} ${f.unit || ''}*`;
      if (f.reference_range) msg += ` (Normal: ${f.reference_range})`;
      msg += `\n`;
      if (f.explanation) msg += `💬 ${f.explanation}\n`;
      if (f.lifestyle_tips?.length) {
        msg += `🥗 Kya karein:\n`;
        f.lifestyle_tips.forEach((t, i) => { msg += `   ${i + 1}. ${t}\n`; });
      }
    });
    msg += `\n`;
  } else {
    msg += `✅ *Saari values normal hain!*\n\n`;
  }

  const questions = abnormal.filter(f => f.doctor_question);
  if (questions.length > 0) {
    msg += `❓ *Doctor se zaroor poochein*\n`;
    msg += `${'─'.repeat(30)}\n`;
    questions.forEach((f, i) => {
      msg += `${i + 1}. ${f.doctor_question}\n`;
    });
    msg += `\n`;
  }

  msg += `${'─'.repeat(30)}\n`;
  msg += `⚕️ _Yeh sirf educational information hai._\n`;
  msg += `_Koi bhi decision lene se pehle doctor se milein._\n`;
  msg += `_Generated by ReportSamjho_`;

  return msg;
}

export default function ResultsScreen({ data, language, onReset }) {
  const [showAbnormalOnly, setShowAbnormalOnly] = useState(false);
  const [allExpanded, setAllExpanded]           = useState(null); // null | true | false
  const [copied, setCopied]                     = useState(false);

  const findings   = data.findings || [];
  const abnormal   = findings.filter(f => f.status !== 'normal');
  const displayed  = showAbnormalOnly ? abnormal : findings;

  const handleWhatsApp = () => {
    const text = encodeURIComponent(buildWhatsAppMessage(data));
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(buildWhatsAppMessage(data));
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // fallback for older browsers
      const ta = document.createElement('textarea');
      ta.value = buildWhatsAppMessage(data);
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  const handlePrint = () => window.print();

  return (
    <div className="min-h-screen flex flex-col bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-100 px-4 py-4 flex items-center justify-between sticky top-0 z-10 print:hidden">
        <div className="flex items-center gap-3">
          <button onClick={onReset} className="text-gray-500 hover:text-gray-800 transition-colors">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </button>
          <div>
            <h2 className="text-lg font-bold text-gray-900">Report<span className="text-[#1D9E75]">Samjho</span></h2>
            <p className="text-xs text-gray-400">{findings.length} parameters found</p>
          </div>
        </div>
        <button onClick={handlePrint} className="text-gray-400 hover:text-gray-700 transition-colors" title="Print report">
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
              d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
          </svg>
        </button>
      </div>

      <div className="max-w-xl mx-auto w-full px-4 py-6 space-y-4">

        {/* Overall Summary */}
        {data.overall_summary && (
          <div className="bg-[#1D9E75] text-white rounded-2xl p-5 shadow-sm">
            <div className="flex items-start gap-3">
              <div className="w-8 h-8 bg-white/20 rounded-xl flex items-center justify-center flex-shrink-0">
                <svg className="w-4 h-4 text-white" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                </svg>
              </div>
              <div>
                <p className="text-xs font-semibold text-white/70 mb-1 uppercase tracking-wide">Overall Summary</p>
                <p className="text-base leading-relaxed">{data.overall_summary}</p>
              </div>
            </div>
          </div>
        )}

        {/* Controls bar */}
        <div className="flex items-center justify-between gap-2 flex-wrap">
          {/* Filter toggle */}
          <button
            onClick={() => setShowAbnormalOnly(v => !v)}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold border transition-all ${
              showAbnormalOnly
                ? 'bg-red-50 text-red-600 border-red-200'
                : 'bg-white text-gray-500 border-gray-200 hover:border-red-300'
            }`}
          >
            <svg className="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd"/>
            </svg>
            {showAbnormalOnly ? `Abnormal only (${abnormal.length})` : 'Show abnormal only'}
          </button>

          {/* Expand/collapse all */}
          <div className="flex gap-2">
            <button
              onClick={() => setAllExpanded(true)}
              className="text-xs text-[#1D9E75] font-medium hover:underline"
            >
              Expand all
            </button>
            <span className="text-gray-300 text-xs">|</span>
            <button
              onClick={() => setAllExpanded(false)}
              className="text-xs text-gray-400 font-medium hover:underline"
            >
              Collapse all
            </button>
          </div>
        </div>

        {/* Finding Cards */}
        {displayed.length === 0 && (
          <div className="bg-white rounded-2xl p-8 text-center text-gray-400">
            {showAbnormalOnly ? 'Koi abnormal value nahi mili 🎉' : 'Koi finding nahi mili.'}
          </div>
        )}
        {displayed.map((finding, i) => (
          <FindingCard key={i} finding={finding} forceExpanded={allExpanded} />
        ))}

        {/* Share block */}
        <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100 print:hidden">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-8 h-8 bg-blue-50 rounded-xl flex items-center justify-center">
              <svg className="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
              </svg>
            </div>
            <div>
              <h3 className="font-bold text-gray-900">Doctor ke liye share karein</h3>
              <p className="text-xs text-gray-400">Full report + doctor questions</p>
            </div>
          </div>

          {/* Preview of message */}
          {abnormal.length > 0 && (
            <div className="bg-gray-50 rounded-xl p-3 mb-4 max-h-32 overflow-y-auto">
              <p className="text-xs text-gray-500 whitespace-pre-line leading-relaxed font-mono">
                {buildWhatsAppMessage(data).substring(0, 300)}...
              </p>
            </div>
          )}

          <div className="flex gap-2">
            <button
              onClick={handleWhatsApp}
              className="flex-1 bg-green-500 hover:bg-green-600 text-white rounded-xl py-3 flex items-center justify-center gap-2 font-semibold text-sm transition-all active:scale-95"
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
              </svg>
              WhatsApp
            </button>
            <button
              onClick={handleCopy}
              className={`flex-1 border rounded-xl py-3 flex items-center justify-center gap-2 font-semibold text-sm transition-all active:scale-95 ${
                copied ? 'bg-[#e8f7f3] border-[#1D9E75] text-[#1D9E75]' : 'bg-white border-gray-200 text-gray-600 hover:border-gray-300'
              }`}
            >
              {copied ? (
                <><svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"/></svg> Copied!</>
              ) : (
                <><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"/></svg> Copy</>
              )}
            </button>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5">
          <div className="flex gap-3">
            <svg className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
            </svg>
            <div>
              <p className="font-semibold text-amber-800 text-sm">Zaroori baat</p>
              <p className="text-amber-700 text-sm mt-1 leading-relaxed">
                Yeh explanation sirf educational purpose ke liye hai. Koi bhi health decision lene se pehle apne doctor se milein.
              </p>
            </div>
          </div>
        </div>

        <button
          onClick={onReset}
          className="w-full bg-white border-2 border-[#1D9E75] text-[#1D9E75] rounded-2xl py-4 font-semibold text-base flex items-center justify-center gap-2 hover:bg-[#e8f7f3] active:scale-95 transition-all print:hidden"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
              d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
          </svg>
          Doosri report analyse karein
        </button>
        <div className="pb-4" />
      </div>
    </div>
  );
}
